import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const countries = [
  // NORTH AMERICA (24)
  { iso2: "US", iso3: "USA", name: "United States", capital: "Washington, D.C.", region: "North America" },
  { iso2: "CA", iso3: "CAN", name: "Canada", capital: "Ottawa", region: "North America" },
  { iso2: "MX", iso3: "MEX", name: "Mexico", capital: "Mexico City", region: "North America" },
  { iso2: "BZ", iso3: "BLZ", name: "Belize", capital: "Belmopan", region: "North America" },
  { iso2: "CR", iso3: "CRI", name: "Costa Rica", capital: "San José", region: "North America" },
  { iso2: "SV", iso3: "SLV", name: "El Salvador", capital: "San Salvador", region: "North America" },
  { iso2: "GT", iso3: "GTM", name: "Guatemala", capital: "Guatemala City", region: "North America" },
  { iso2: "HN", iso3: "HND", name: "Honduras", capital: "Tegucigalpa", region: "North America" },
  { iso2: "NI", iso3: "NIC", name: "Nicaragua", capital: "Managua", region: "North America" },
  { iso2: "PA", iso3: "PAN", name: "Panama", capital: "Panama City", region: "North America" },
  { iso2: "AG", iso3: "ATG", name: "Antigua and Barbuda", capital: "Saint John's", region: "North America" },
  { iso2: "BS", iso3: "BHS", name: "Bahamas", capital: "Nassau", region: "North America" },
  { iso2: "BB", iso3: "BRB", name: "Barbados", capital: "Bridgetown", region: "North America" },
  { iso2: "DM", iso3: "DMA", name: "Dominica", capital: "Roseau", region: "North America" },
  { iso2: "DO", iso3: "DOM", name: "Dominican Republic", capital: "Santo Domingo", region: "North America" },
  { iso2: "GD", iso3: "GRD", name: "Grenada", capital: "Saint George's", region: "North America" },
  { iso2: "HT", iso3: "HTI", name: "Haiti", capital: "Port-au-Prince", region: "North America" },
  { iso2: "JM", iso3: "JAM", name: "Jamaica", capital: "Kingston", region: "North America" },
  { iso2: "KN", iso3: "KNA", name: "Saint Kitts and Nevis", capital: "Basseterre", region: "North America" },
  { iso2: "LC", iso3: "LCA", name: "Saint Lucia", capital: "Castries", region: "North America" },
  { iso2: "VC", iso3: "VCT", name: "Saint Vincent and the Grenadines", capital: "Kingstown", region: "North America" },
  { iso2: "TT", iso3: "TTO", name: "Trinidad and Tobago", capital: "Port of Spain", region: "North America" },
  { iso2: "CU", iso3: "CUB", name: "Cuba", capital: "Havana", region: "North America" },
  { iso2: "PM", iso3: "SPM", name: "Saint Pierre and Miquelon", capital: "Saint-Pierre", region: "North America" },
  // SOUTH AMERICA (13)
  { iso2: "AR", iso3: "ARG", name: "Argentina", capital: "Buenos Aires", region: "South America" },
  { iso2: "BO", iso3: "BOL", name: "Bolivia", capital: "La Paz", region: "South America" },
  { iso2: "BR", iso3: "BRA", name: "Brazil", capital: "Brasília", region: "South America" },
  { iso2: "CL", iso3: "CHL", name: "Chile", capital: "Santiago", region: "South America" },
  { iso2: "CO", iso3: "COL", name: "Colombia", capital: "Bogotá", region: "South America" },
  { iso2: "EC", iso3: "ECU", name: "Ecuador", capital: "Quito", region: "South America" },
  { iso2: "GY", iso3: "GUY", name: "Guyana", capital: "Georgetown", region: "South America" },
  { iso2: "PY", iso3: "PRY", name: "Paraguay", capital: "Asunción", region: "South America" },
  { iso2: "PE", iso3: "PER", name: "Peru", capital: "Lima", region: "South America" },
  { iso2: "SR", iso3: "SUR", name: "Suriname", capital: "Paramaribo", region: "South America" },
  { iso2: "UY", iso3: "URY", name: "Uruguay", capital: "Montevideo", region: "South America" },
  { iso2: "VE", iso3: "VEN", name: "Venezuela", capital: "Caracas", region: "South America" },
  { iso2: "FK", iso3: "FLK", name: "Falkland Islands", capital: "Stanley", region: "South America" },
  // ASIA (47)
  { iso2: "AF", iso3: "AFG", name: "Afghanistan", capital: "Kabul", region: "Asia" },
  { iso2: "AZ", iso3: "AZE", name: "Azerbaijan", capital: "Baku", region: "Asia" },
  { iso2: "BH", iso3: "BHR", name: "Bahrain", capital: "Manama", region: "Asia" },
  { iso2: "BD", iso3: "BGD", name: "Bangladesh", capital: "Dhaka", region: "Asia" },
  { iso2: "BT", iso3: "BTN", name: "Bhutan", capital: "Thimphu", region: "Asia" },
  { iso2: "BN", iso3: "BRN", name: "Brunei", capital: "Bandar Seri Begawan", region: "Asia" },
  { iso2: "KH", iso3: "KHM", name: "Cambodia", capital: "Phnom Penh", region: "Asia" },
  { iso2: "CN", iso3: "CHN", name: "China", capital: "Beijing", region: "Asia" },
  { iso2: "GE", iso3: "GEO", name: "Georgia", capital: "Tbilisi", region: "Asia" },
  { iso2: "HK", iso3: "HKG", name: "Hong Kong", capital: "Victoria City", region: "Asia" },
  { iso2: "IN", iso3: "IND", name: "India", capital: "New Delhi", region: "Asia" },
  { iso2: "ID", iso3: "IDN", name: "Indonesia", capital: "Jakarta", region: "Asia" },
  { iso2: "IR", iso3: "IRN", name: "Iran", capital: "Tehran", region: "Asia" },
  { iso2: "IQ", iso3: "IRQ", name: "Iraq", capital: "Baghdad", region: "Asia" },
  { iso2: "IL", iso3: "ISR", name: "Israel", capital: "Jerusalem", region: "Asia" },
  { iso2: "JP", iso3: "JPN", name: "Japan", capital: "Tokyo", region: "Asia" },
  { iso2: "JO", iso3: "JOR", name: "Jordan", capital: "Amman", region: "Asia" },
  { iso2: "KZ", iso3: "KAZ", name: "Kazakhstan", capital: "Nur-Sultan", region: "Asia" },
  { iso2: "KP", iso3: "PRK", name: "North Korea", capital: "Pyongyang", region: "Asia" },
  { iso2: "KR", iso3: "KOR", name: "South Korea", capital: "Seoul", region: "Asia" },
  { iso2: "KW", iso3: "KWT", name: "Kuwait", capital: "Kuwait City", region: "Asia" },
  { iso2: "KG", iso3: "KGZ", name: "Kyrgyzstan", capital: "Bishkek", region: "Asia" },
  { iso2: "LA", iso3: "LAO", name: "Laos", capital: "Vientiane", region: "Asia" },
  { iso2: "LB", iso3: "LBN", name: "Lebanon", capital: "Beirut", region: "Asia" },
  { iso2: "MO", iso3: "MAC", name: "Macau", capital: "Macau", region: "Asia" },
  { iso2: "MY", iso3: "MYS", name: "Malaysia", capital: "Kuala Lumpur", region: "Asia" },
  { iso2: "MV", iso3: "MDV", name: "Maldives", capital: "Malé", region: "Asia" },
  { iso2: "MN", iso3: "MNG", name: "Mongolia", capital: "Ulaanbaatar", region: "Asia" },
  { iso2: "MM", iso3: "MMR", name: "Myanmar", capital: "Naypyidaw", region: "Asia" },
  { iso2: "NP", iso3: "NPL", name: "Nepal", capital: "Kathmandu", region: "Asia" },
  { iso2: "OM", iso3: "OMN", name: "Oman", capital: "Muscat", region: "Asia" },
  { iso2: "PK", iso3: "PAK", name: "Pakistan", capital: "Islamabad", region: "Asia" },
  { iso2: "PH", iso3: "PHL", name: "Philippines", capital: "Manila", region: "Asia" },
  { iso2: "QA", iso3: "QAT", name: "Qatar", capital: "Doha", region: "Asia" },
  { iso2: "SA", iso3: "SAU", name: "Saudi Arabia", capital: "Riyadh", region: "Asia" },
  { iso2: "SG", iso3: "SGP", name: "Singapore", capital: "Singapore", region: "Asia" },
  { iso2: "LK", iso3: "LKA", name: "Sri Lanka", capital: "Colombo", region: "Asia" },
  { iso2: "SY", iso3: "SYR", name: "Syria", capital: "Damascus", region: "Asia" },
  { iso2: "TW", iso3: "TWN", name: "Taiwan", capital: "Taipei", region: "Asia" },
  { iso2: "TJ", iso3: "TJK", name: "Tajikistan", capital: "Dushanbe", region: "Asia" },
  { iso2: "TH", iso3: "THA", name: "Thailand", capital: "Bangkok", region: "Asia" },
  { iso2: "TL", iso3: "TLS", name: "Timor-Leste", capital: "Dili", region: "Asia" },
  { iso2: "TR", iso3: "TUR", name: "Turkey", capital: "Ankara", region: "Asia" },
  { iso2: "TM", iso3: "TKM", name: "Turkmenistan", capital: "Ashgabat", region: "Asia" },
  { iso2: "AE", iso3: "ARE", name: "United Arab Emirates", capital: "Abu Dhabi", region: "Asia" },
  { iso2: "UZ", iso3: "UZB", name: "Uzbekistan", capital: "Tashkent", region: "Asia" },
  { iso2: "VN", iso3: "VNM", name: "Vietnam", capital: "Hanoi", region: "Asia" },
  { iso2: "YE", iso3: "YEM", name: "Yemen", capital: "Sana'a", region: "Asia" },
  // EUROPE (47)
  { iso2: "AL", iso3: "ALB", name: "Albania", capital: "Tirana", region: "Europe" },
  { iso2: "AD", iso3: "AND", name: "Andorra", capital: "Andorra la Vella", region: "Europe" },
  { iso2: "AT", iso3: "AUT", name: "Austria", capital: "Vienna", region: "Europe" },
  { iso2: "BY", iso3: "BLR", name: "Belarus", capital: "Minsk", region: "Europe" },
  { iso2: "BE", iso3: "BEL", name: "Belgium", capital: "Brussels", region: "Europe" },
  { iso2: "BA", iso3: "BIH", name: "Bosnia and Herzegovina", capital: "Sarajevo", region: "Europe" },
  { iso2: "BG", iso3: "BGR", name: "Bulgaria", capital: "Sofia", region: "Europe" },
  { iso2: "HR", iso3: "HRV", name: "Croatia", capital: "Zagreb", region: "Europe" },
  { iso2: "CY", iso3: "CYP", name: "Cyprus", capital: "Nicosia", region: "Europe" },
  { iso2: "CZ", iso3: "CZE", name: "Czech Republic", capital: "Prague", region: "Europe" },
  { iso2: "DK", iso3: "DNK", name: "Denmark", capital: "Copenhagen", region: "Europe" },
  { iso2: "EE", iso3: "EST", name: "Estonia", capital: "Tallinn", region: "Europe" },
  { iso2: "FI", iso3: "FIN", name: "Finland", capital: "Helsinki", region: "Europe" },
  { iso2: "FR", iso3: "FRA", name: "France", capital: "Paris", region: "Europe" },
  { iso2: "DE", iso3: "DEU", name: "Germany", capital: "Berlin", region: "Europe" },
  { iso2: "GR", iso3: "GRC", name: "Greece", capital: "Athens", region: "Europe" },
  { iso2: "HU", iso3: "HUN", name: "Hungary", capital: "Budapest", region: "Europe" },
  { iso2: "IS", iso3: "ISL", name: "Iceland", capital: "Reykjavik", region: "Europe" },
  { iso2: "IE", iso3: "IRL", name: "Ireland", capital: "Dublin", region: "Europe" },
  { iso2: "IT", iso3: "ITA", name: "Italy", capital: "Rome", region: "Europe" },
  { iso2: "XK", iso3: "XKX", name: "Kosovo", capital: "Pristina", region: "Europe" },
  { iso2: "LV", iso3: "LVA", name: "Latvia", capital: "Riga", region: "Europe" },
  { iso2: "LI", iso3: "LIE", name: "Liechtenstein", capital: "Vaduz", region: "Europe" },
  { iso2: "LT", iso3: "LTU", name: "Lithuania", capital: "Vilnius", region: "Europe" },
  { iso2: "LU", iso3: "LUX", name: "Luxembourg", capital: "Luxembourg City", region: "Europe" },
  { iso2: "MT", iso3: "MLT", name: "Malta", capital: "Valletta", region: "Europe" },
  { iso2: "MD", iso3: "MDA", name: "Moldova", capital: "Chișinău", region: "Europe" },
  { iso2: "MC", iso3: "MCO", name: "Monaco", capital: "Monaco", region: "Europe" },
  { iso2: "ME", iso3: "MNE", name: "Montenegro", capital: "Podgorica", region: "Europe" },
  { iso2: "NL", iso3: "NLD", name: "Netherlands", capital: "Amsterdam", region: "Europe" },
  { iso2: "NO", iso3: "NOR", name: "Norway", capital: "Oslo", region: "Europe" },
  { iso2: "PL", iso3: "POL", name: "Poland", capital: "Warsaw", region: "Europe" },
  { iso2: "PT", iso3: "PRT", name: "Portugal", capital: "Lisbon", region: "Europe" },
  { iso2: "RO", iso3: "ROU", name: "Romania", capital: "Bucharest", region: "Europe" },
  { iso2: "RU", iso3: "RUS", name: "Russia", capital: "Moscow", region: "Europe" },
  { iso2: "SM", iso3: "SMR", name: "San Marino", capital: "San Marino", region: "Europe" },
  { iso2: "RS", iso3: "SRB", name: "Serbia", capital: "Belgrade", region: "Europe" },
  { iso2: "SK", iso3: "SVK", name: "Slovakia", capital: "Bratislava", region: "Europe" },
  { iso2: "SI", iso3: "SVN", name: "Slovenia", capital: "Ljubljana", region: "Europe" },
  { iso2: "ES", iso3: "ESP", name: "Spain", capital: "Madrid", region: "Europe" },
  { iso2: "SE", iso3: "SWE", name: "Sweden", capital: "Stockholm", region: "Europe" },
  { iso2: "CH", iso3: "CHE", name: "Switzerland", capital: "Bern", region: "Europe" },
  { iso2: "UA", iso3: "UKR", name: "Ukraine", capital: "Kyiv", region: "Europe" },
  { iso2: "GB", iso3: "GBR", name: "United Kingdom", capital: "London", region: "Europe" },
  { iso2: "VA", iso3: "VAT", name: "Vatican City", capital: "Vatican City", region: "Europe" },
  // OCEANIA (17)
  { iso2: "AU", iso3: "AUS", name: "Australia", capital: "Canberra", region: "Oceania" },
  { iso2: "FJ", iso3: "FJI", name: "Fiji", capital: "Suva", region: "Oceania" },
  { iso2: "KI", iso3: "KIR", name: "Kiribati", capital: "Tarawa", region: "Oceania" },
  { iso2: "MH", iso3: "MHL", name: "Marshall Islands", capital: "Majuro", region: "Oceania" },
  { iso2: "FM", iso3: "FSM", name: "Micronesia", capital: "Palikir", region: "Oceania" },
  { iso2: "NR", iso3: "NRU", name: "Nauru", capital: "Yaren", region: "Oceania" },
  { iso2: "NZ", iso3: "NZL", name: "New Zealand", capital: "Wellington", region: "Oceania" },
  { iso2: "PW", iso3: "PLW", name: "Palau", capital: "Ngerulmud", region: "Oceania" },
  { iso2: "PG", iso3: "PNG", name: "Papua New Guinea", capital: "Port Moresby", region: "Oceania" },
  { iso2: "WS", iso3: "WSM", name: "Samoa", capital: "Apia", region: "Oceania" },
  { iso2: "SB", iso3: "SLB", name: "Solomon Islands", capital: "Honiara", region: "Oceania" },
  { iso2: "TO", iso3: "TON", name: "Tonga", capital: "Nuku'alofa", region: "Oceania" },
  { iso2: "TV", iso3: "TUV", name: "Tuvalu", capital: "Funafuti", region: "Oceania" },
  { iso2: "VU", iso3: "VUT", name: "Vanuatu", capital: "Port Vila", region: "Oceania" },
  { iso2: "PF", iso3: "PYF", name: "French Polynesia", capital: "Papeete", region: "Oceania" },
  { iso2: "GU", iso3: "GUM", name: "Guam", capital: "Hagatna", region: "Oceania" },
  { iso2: "NC", iso3: "NCL", name: "New Caledonia", capital: "Nouméa", region: "Oceania" },
  // AFRICA (55)
  { iso2: "DZ", iso3: "DZA", name: "Algeria", capital: "Algiers", region: "Africa" },
  { iso2: "AO", iso3: "AGO", name: "Angola", capital: "Luanda", region: "Africa" },
  { iso2: "BJ", iso3: "BEN", name: "Benin", capital: "Porto-Novo", region: "Africa" },
  { iso2: "BW", iso3: "BWA", name: "Botswana", capital: "Gaborone", region: "Africa" },
  { iso2: "BF", iso3: "BFA", name: "Burkina Faso", capital: "Ouagadougou", region: "Africa" },
  { iso2: "BI", iso3: "BDI", name: "Burundi", capital: "Gitega", region: "Africa" },
  { iso2: "CM", iso3: "CMR", name: "Cameroon", capital: "Yaoundé", region: "Africa" },
  { iso2: "CV", iso3: "CPV", name: "Cape Verde", capital: "Praia", region: "Africa" },
  { iso2: "CF", iso3: "CAF", name: "Central African Republic", capital: "Bangui", region: "Africa" },
  { iso2: "TD", iso3: "TCD", name: "Chad", capital: "N'Djamena", region: "Africa" },
  { iso2: "KM", iso3: "COM", name: "Comoros", capital: "Moroni", region: "Africa" },
  { iso2: "CG", iso3: "COG", name: "Congo", capital: "Brazzaville", region: "Africa" },
  { iso2: "CD", iso3: "COD", name: "Democratic Republic of the Congo", capital: "Kinshasa", region: "Africa" },
  { iso2: "CI", iso3: "CIV", name: "Côte d'Ivoire", capital: "Yamoussoukro", region: "Africa" },
  { iso2: "DJ", iso3: "DJI", name: "Djibouti", capital: "Djibouti", region: "Africa" },
  { iso2: "EG", iso3: "EGY", name: "Egypt", capital: "Cairo", region: "Africa" },
  { iso2: "GQ", iso3: "GNQ", name: "Equatorial Guinea", capital: "Malabo", region: "Africa" },
  { iso2: "ER", iso3: "ERI", name: "Eritrea", capital: "Asmara", region: "Africa" },
  { iso2: "ET", iso3: "ETH", name: "Ethiopia", capital: "Addis Ababa", region: "Africa" },
  { iso2: "GA", iso3: "GAB", name: "Gabon", capital: "Libreville", region: "Africa" },
  { iso2: "GM", iso3: "GMB", name: "Gambia", capital: "Banjul", region: "Africa" },
  { iso2: "GH", iso3: "GHA", name: "Ghana", capital: "Accra", region: "Africa" },
  { iso2: "GN", iso3: "GIN", name: "Guinea", capital: "Conakry", region: "Africa" },
  { iso2: "GW", iso3: "GNB", name: "Guinea-Bissau", capital: "Bissau", region: "Africa" },
  { iso2: "KE", iso3: "KEN", name: "Kenya", capital: "Nairobi", region: "Africa" },
  { iso2: "LS", iso3: "LSO", name: "Lesotho", capital: "Maseru", region: "Africa" },
  { iso2: "LR", iso3: "LBR", name: "Liberia", capital: "Monrovia", region: "Africa" },
  { iso2: "LY", iso3: "LBY", name: "Libya", capital: "Tripoli", region: "Africa" },
  { iso2: "MG", iso3: "MDG", name: "Madagascar", capital: "Antananarivo", region: "Africa" },
  { iso2: "MW", iso3: "MWI", name: "Malawi", capital: "Lilongwe", region: "Africa" },
  { iso2: "ML", iso3: "MLI", name: "Mali", capital: "Bamako", region: "Africa" },
  { iso2: "MR", iso3: "MRT", name: "Mauritania", capital: "Nouakchott", region: "Africa" },
  { iso2: "MU", iso3: "MUS", name: "Mauritius", capital: "Port Louis", region: "Africa" },
  { iso2: "MA", iso3: "MAR", name: "Morocco", capital: "Rabat", region: "Africa" },
  { iso2: "MZ", iso3: "MOZ", name: "Mozambique", capital: "Maputo", region: "Africa" },
  { iso2: "NA", iso3: "NAM", name: "Namibia", capital: "Windhoek", region: "Africa" },
  { iso2: "NE", iso3: "NER", name: "Niger", capital: "Niamey", region: "Africa" },
  { iso2: "NG", iso3: "NGA", name: "Nigeria", capital: "Abuja", region: "Africa" },
  { iso2: "RW", iso3: "RWA", name: "Rwanda", capital: "Kigali", region: "Africa" },
  { iso2: "ST", iso3: "STP", name: "São Tomé and Príncipe", capital: "São Tomé", region: "Africa" },
  { iso2: "SN", iso3: "SEN", name: "Senegal", capital: "Dakar", region: "Africa" },
  { iso2: "SC", iso3: "SYC", name: "Seychelles", capital: "Victoria", region: "Africa" },
  { iso2: "SL", iso3: "SLE", name: "Sierra Leone", capital: "Freetown", region: "Africa" },
  { iso2: "SO", iso3: "SOM", name: "Somalia", capital: "Mogadishu", region: "Africa" },
  { iso2: "ZA", iso3: "ZAF", name: "South Africa", capital: "Pretoria", region: "Africa" },
  { iso2: "SS", iso3: "SSD", name: "South Sudan", capital: "Juba", region: "Africa" },
  { iso2: "SD", iso3: "SDN", name: "Sudan", capital: "Khartoum", region: "Africa" },
  { iso2: "SZ", iso3: "SWZ", name: "Eswatini", capital: "Mbabane", region: "Africa" },
  { iso2: "TZ", iso3: "TZA", name: "Tanzania", capital: "Dar es Salaam", region: "Africa" },
  { iso2: "TG", iso3: "TGO", name: "Togo", capital: "Lomé", region: "Africa" },
  { iso2: "TN", iso3: "TUN", name: "Tunisia", capital: "Tunis", region: "Africa" },
  { iso2: "UG", iso3: "UGA", name: "Uganda", capital: "Kampala", region: "Africa" },
  { iso2: "ZM", iso3: "ZMB", name: "Zambia", capital: "Lusaka", region: "Africa" },
  { iso2: "ZW", iso3: "ZWE", name: "Zimbabwe", capital: "Harare", region: "Africa" },
  { iso2: "MU", iso3: "MUS", name: "Mauritius", capital: "Port Louis", region: "Africa" },
];

async function main() {
  console.log("🌍 Starting to seed countries...");
  let created = 0;

  for (const country of countries) {
    try {
      await prisma.country.upsert({
        where: { id: country.iso2 },
        update: country,
        create: {
          id: country.iso2,
          name: country.name,
          capital: country.capital,
          region: country.region,
          iso2: country.iso2,
          iso3: country.iso3,
          flagUrl: `https://flagcdn.com/w320/${country.iso2.toLowerCase()}.png`,
          svgPath: "", // Will be populated by separate SVG mapping
        },
      });
      created++;
    } catch (e) {
      console.error(`Error seeding ${country.name}:`, e);
    }
  }

  console.log(`✅ Seeded ${created} countries!`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
